import type { CommunityPost } from './types';

export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 1,
    type: 'free',
    author: {
      initial: 'U',
      nickname: '유저닉네임_01',
      personalityTag: '오픈월드러',
    },
    timeAgo: '2시간 전',
    title: '오픈월드 RPG 다음 작품 뭐가 좋을까요? 위처 3 끝낸 직후입니다',
    bodyPreview:
      '엘든 링은 너무 어려워 보이고… 잔잔한 톤의 오픈월드 RPG로 추천 부탁드려요. 한글화 필수입니다.',
    gameName: '위처 3',
    voteCount: 142,
    isVoted: true,
    commentCount: 28,
  },
  {
    id: 2,
    type: 'review',
    author: {
      initial: 'M',
      nickname: '유저닉네임_02',
      personalityTag: '스토리 마니아',
    },
    timeAgo: '5시간 전',
    title: '이 게임, 엔딩에서 진짜 울었습니다',
    bodyPreview:
      '스토리 마지막 챕터의 분기 선택이 정말 무겁게 다가왔어요. 동료 캐릭터 각각 서사가 살아있고…',
    gameName: '게임 타이틀 01',
    voteCount: 211,
    isVoted: false,
    commentCount: 47,
    starRating: '★ ★ ★ ★ ★',
    genre: 'RPG · 오픈월드',
    playHours: '47시간 플레이',
    clearStatus: '메인 클리어',
  },
  {
    id: 3,
    type: 'party',
    author: {
      initial: 'K',
      nickname: '유저닉네임_03',
      personalityTag: '하드코어',
    },
    timeAgo: '1시간 전',
    title: '주말 저녁 협동 레이드 같이 도실 분 🛡️',
    gameName: '게임 타이틀 02',
    voteCount: 38,
    isVoted: false,
    commentCount: 28,
    timeSlot: '토 21:00~24:00',
    mode: '4인 협동 · 레이드',
    currentMembers: 2,
    maxMembers: 4,
  },
  {
    id: 4,
    type: 'free',
    author: {
      initial: 'S',
      nickname: '유저닉네임_04',
      personalityTag: '인디 헌터',
    },
    timeAgo: '6시간 전',
    title: '이번 주말에 한 인디 게임 추천',
    bodyPreview:
      '짧게 3시간이면 클리어 가능한데 여운은 길게 남아요. 가격도 ₩9,900으로 부담 없고…',
    gameName: '인디 게임 01',
    voteCount: 89,
    isVoted: false,
    commentCount: 14,
  },
  {
    id: 5,
    type: 'review',
    author: {
      initial: 'P',
      nickname: '유저닉네임_05',
      personalityTag: '전략가',
    },
    timeAgo: '12시간 전',
    title: '전략 시뮬 좋아하시면 정말 강추',
    bodyPreview:
      '초반 진입장벽이 좀 있지만 시스템에 익숙해지면 손을 못 떼게 됩니다. 다만 후반에 컨텐츠 반복은…',
    gameName: '게임 타이틀 04',
    voteCount: 76,
    isVoted: false,
    commentCount: 19,
    starRating: '★ ★ ★ ★ ☆',
    genre: '전략 시뮬',
    playHours: '32시간 플레이',
    clearStatus: '진행 중',
  },
  {
    id: 6,
    type: 'guide',
    author: {
      initial: 'Y',
      nickname: '유저닉네임_06',
      personalityTag: '공략왕',
    },
    timeAgo: '1일 전',
    title: '[초보 가이드] 첫 10시간 동안 꼭 해야 할 것 5가지',
    bodyPreview:
      '메인 퀘스트를 잠시 미루고 거점을 먼저 잡으세요. 광물 채집은 2지역까지 진행한 후에…',
    gameName: '게임 타이틀 01',
    voteCount: 312,
    isVoted: false,
    commentCount: 64,
    pinned: true,
  },
  {
    id: 7,
    type: 'party',
    author: {
      initial: 'N',
      nickname: '유저닉네임_07',
      personalityTag: '캐주얼',
    },
    timeAgo: '3시간 전',
    title: '오늘 저녁 처음 입문하시는 분 같이 해요',
    gameName: '게임 타이틀 03',
    voteCount: 22,
    isVoted: false,
    commentCount: 8,
    timeSlot: '오늘 20:00~22:00',
    mode: '2인 코옵 · 초보 환영',
    currentMembers: 2,
    maxMembers: 2,
  },
  {
    id: 8,
    type: 'notice',
    author: {
      initial: 'G',
      nickname: 'GAMBITI',
      personalityTag: '운영자',
      isAdmin: true,
    },
    timeAgo: '2일 전',
    title: '📢 커뮤니티 운영 가이드라인 안내',
    bodyPreview:
      '건전한 커뮤니티 문화를 위해 몇 가지 규칙을 안내드립니다. 모두 즐겁게 이용해주세요.',
    voteCount: 0,
    isVoted: false,
    commentCount: 142,
    pinned: true,
  },
];

export const MOCK_REMAINING_COUNT = 1239;
