name: Gemini Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Gemini AI Review
        # 깃헙에 공개된 신뢰할 수 있는 제마이내 리뷰어 액션을 가져옵니다
        uses: google-gemini/gemini-github-actions/code-review@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
